#!/bin/bash

cmd="$1"
shift
args="$@"

pass=0

run_test(){
	num=$1
	expected=$2
	got=$("$cmd" "$args")
	if cmp -s <(echo $got) <(echo $expected); then
		echo "Test #$num: $(printf '\e[1;32mPASS\e[0m')"
		pass=$((pass + 1))
	else
		echo "Test #$num: $(printf '\e[1;31mFAIL\e[0m') Expected: $expected, got: $got"
	fi
}

run_test 1 $'
A B C D

B A
' <<EOD
A B
B A
B C
C D
D C

A D
C A
B A
EOD

run_test 2 $'
A B D
H B C F
G B I
G B H
J A I
' <<EOD
A B
A E
A G
A I
B A
B C
B D
B E
B G
B H
B I
C B
C D
C E
C F
C G
C J
D A
D B
D E
D G
E A
E B
E C
E D
E G
E H
E I
E J
F C
F G
F I
G B
G D
G E
H A
H B
H D
H E
H G
H I
I B
I E
I G
J A
J B
J C
J E
J G

A D
H F
G I
G H
J I
EOD

run_test 3 $'
A C E F H

H G F

A C D
' <<EOD
A B
A C
B A
C D
C E
D B
D E
E B
E C
E D
E F
F H
F G
G F
G H
H G

A H
H A
H F
F B
A D
EOD

run_test 4 $'
I J H B G C A
A B G J M
L F D G C A B
A B G L
E L F D G C A B I
' <<EOD
A B
A C
A D
B I
B H
B G
C A
C H
C G
C F
D G
D F
D E
E L
F D
F K
F L
G C
G J
G K
G L
H B
H J
H K
I J
J H
J M
K G
K M
L F
L M

I A
A M
L B
A L
E I
EOD

run_test 5 $'
S O J K L F G
R N P B C D F M
K J O N P B
C G
H B C G I J K
' <<EOD
A B
B A
B C
C D
C G
D E
D F
E D
F G
F M
G H
G I
H B
H N
I J
I L
J K
J O
K J
K L
K M
L F
M F
N P
N R
O J
O N
O S
P B
P Q
Q P
R N
S O

S G
R M
K B
C G
H K
EOD

echo "$pass/$num passed"
